# ============================
# 1. PDE problem configs
# ============================
problem:
  type: diffusion                    # the problem type of PDE, "diffusion" or "convdiff"
  method: fdm                        # the numerical method to get training data, "fdm"
  n_dim: 1                           # the dimension of the input of PDEs
  output_dim: 1                      # the dimension of the solutions
  iteration: 700                     # the maximal iterations for the hybrid solver
  tolerance: !!float 1e-10           # tolerance for residual of the hybrid solver
 # grid_num: 201                      # Mesh size for unresolved problems

# =================================================================================
# 2.1 Data generation configs (Generate Training & Validation Data for Neural Operator)
# =================================================================================
data:                                # The setting of mesh in training data
  func_num: 10000                    # the count of data in the overall dataset (including training and validating)
  train_ratio: 0.90                  # the ratio of training data over all data, remaining is the validating data
  threshold: 1.0                     # placeholder, meaningful only for Helmholtz equations
  redundancy: 1.0                    # placeholder, meaningful only for Helmholtz equations

  mesh:
    grid_num: 31                     # the num of discrete uniform gird points for k(x), f(x), u(x)
    grid_type: uniform               # uniform grid: "uniform" & non-uniform grid: "power", "tanh"

  k_x:                               # The GRFs parameter for parameter function k(x)
    generator: grf                   # "fixed" or "grf"
    grf_setting:
      sigma: [0.3,]                  # influence amplitude of GRF, default: 0.3, large -> large amplitude
      l0: [0.1,]                     # influence frequency of GRF, default: 0.1, less -> high frequency
      mean: 1.0                      # mean value of k(x)
      minimal: 0.3                   # minimal value of k(x)
    fixed_setting:
      value: 1.0                     # value of constant k(x)

  f_x:                               # The parameter for parameter function f(x)
      generator: grf                 # fourier, grf, gaussian, or fixed
      grf_setting:                   # The GRFs parameter for parameter function k(x) (meaningless for Fourier and Gaussian)
        sigma: [1.0,]                # large -> large amplitude, default: 1.0
        l0: [0.1,]                   # less -> high frequency, default: 0.1
      gaussian_setting:
        standard: True               # default to be standard normal distribution
      fixed_setting:
        value: 1.0                   # value of constant f(x)
      fourier_setting:
        freq_num: 3                  # the number for overlapping sine and cosine functions
        freq_upper: 10               # the upper bound of frequency
        amplitude: 0.5               # the upper bound of amplitude


# ============================
# 2.2 Testing data generation
# ============================
testing:
  func_num: 30                       # size of testing data (number of k_x, while f_x = len(f_x.generator) * func_num)
  threshold: 1.0                     # placeholder, meaningful only for Helmholtz equations
  redundancy: 1.0                    # placeholder, meaningful only for Helmholtz equations

  mesh:
    grid_num: 201                    # testing meshes differ from the training mesh such as [61, 241, 481]
    grid_type: uniform               # default to the same as training; can be customized
  k_x:                               # keep the same generation setting as training by default
    generator: grf
    grf_setting:
      sigma: [0.3,]
      l0: [0.1,]
      mean: 1.0
      minimal: 0.3
    fixed_setting:
      value: 1.0
  f_x:
    generator: [grf, fixed, gaussian, ]  # rhs generation types to mix for testing
    gaussian_setting:                      # gaussian: f ~ N(0,1)
      standard: True                       # au: f = Au where u ~ N(0,1)
    fixed_setting:                         # fixed: f = 1
      value: 1.0
    grf_setting:                           # grf: gaussian random field
      sigma: [ 1.0, ]                      # same parameter as training data by default
      l0: [ 0.1, ]


# ============================
# 3. Neural operator training
# ============================
training:
  mode: static                      # "static" or "dynamic"
  operator_type: FNS           # Neural Operator Type ("DeepONet", "MIONet", "FNS")
  batch_size: 1024                  # batch size
  num_epoch: 20000                 # Epoch num
  lr: 0.0001                        # learning rate
  weight_decay: !!float 1e-8        # weight decay

  loss:
    type: Residual                  # the type of loss function (Residual, Error)
    norm: l2                        # norm type ("l1“, "l2", "h1")
    relative: true                  # whether to use relative error/residual (e.g. ||e||/||u_true||)
    relative_eps: !!float 1e-12     # epsilon to avoid divide-by-zero in relative losses
    grad_alpha: 0.1                 # weight for gradient term
    use_autograd: false             # for static trainer: True -> use model-provided du; False -> FD
                                    # for dynamic trainer: True/False -> FD

  don_setting:                      # configs for DeepONet/MIONet (Meaningless for FNS)
    f_dim: 80                       # the dimension for output of branch_net & trunk_net
    hard_cons: True                 # whether to apply the hard constraints in the neural network

  fns_setting:
    act: "gelu"
    hidden: 32
    hard_cons: False                # whether to apply the hard constraints in the neural network

  dynamic:                          # dynamic training settings (not used in static)
    horizon_size: 5                 # the num of future step in dynamic training framework
    curriculum:                     # curriculum learning
      enabled: true                 # true/True or false/False
      update_interval: 2000         # horizon++ for each update interval


# ==========================================================
# 4. Configs of the hybrid solver
# ==========================================================
solver:
  type: Hybrid                              # "Hybrid", "Numerical", "Neural"
  numerical:
    method: jacobi                             # the numerical solver, "jacobi" or "GS"
    relaxation_factor:  0.6                    # the relaxation coefficient for the classical smoother
    numerical_update: fixed                    # fixed | aa | am
    AA:
      m: 10
      reg: 1e-16

  hybrid:
    update_ratio: 20                           # Ratio of classical to neural updates
    neural_update: fixed                       # "fixed" (size = 1), "cg" (size = p.Tr/p.TAp), "aa" (anderson acc.)
    AA:
      m: 10                                     # the size of aa's history (If use aa to update)
      reg: 1e-10                               # the regularization term

#  eigen_tracking:
#    enabled: False                             # Whether to track eigen-mode loss during iterations
#    modes_of_interest: [1, 3, 5, 10]           # the indices of eigen-mode

## the configs of MG (not discussed in our paper)
#smoother_type: hybrid-jacobi                  # gs, jacobi, hybrid-gs, or hybrid-jacobi
#n_pre: 10                                     # the number of iterations of pre-smoother
#n_post: 10                                    # the number of iterations of post-smoother
#max_levels: 8                                 # the number of different levels of grids
#ratio_MG: 10                                  # the iteration steps for jacobi/deeponet